databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails
    plan: free
    env: ruby
    rootDir: backend-rails
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
