default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: db
  port: 5432

development:
 <<: *default
 database: group_habits_db

test:
 <<: *default
 database: group_habits_db_test

production:
 <<: *default
 url: <%= ENV['DATABASE_URL'] %>
