default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: db
  port: 5432

development:
 <<: *default
 url: <%= ENV['DATABASE_URL'] %>

test:
 <<: *default
 url: <%= ENV['TEST_DATABASE_URL'] %>

production:
 <<: *default
 url: <%= ENV['DATABASE_URL'] %>
