version: '3.0'

services:
  web:
    build: .
    entrypoint: >
      bash -c "
      rm -f tmp/pids/server.pid
      && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - 3000:3000
    volumes:
      - .:/src/myapp
    depends_on:
      - db
    links:
      - "db:db"
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/group_habits_db'
      TEST_DATABASE_URL: 'postgres://postgres:postgres@db:5432/group_habits_db_test'

  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db_data:
