name: Coveralls

on:
  push:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/code_coverage.yml 
  pull_request:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/code_coverage.yml 

jobs:
 test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 23, 29]
    
    defaults:
      run:
        working-directory: android-so    
        
        
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: gradle jacocoTestReport coveralls
