name: Coveralls

on:
  push:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/code_coverage.yml 
  pull_request:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/code_coverage.yml 

jobs:
 android-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-so
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport coveralls
