name: Coveralls

on:
  push:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/code_coverage.yml 
  pull_request:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/code_coverage.yml 

jobs:
 test:

    runs-on: macos-latest
    
    defaults:
      run:
        working-directory: android-so

    steps:
     - uses: actions/checkout@v3
     - name: set up JDK 11
       uses: actions/setup-java@v3
       with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
     - name: Run Tests
       env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
       uses: reactivecircus/android-emulator-runner@v2
       with:
        
          api-level: 29
          script: ./gradle app:coveralls
