name: Android Coveralls

on:
  push:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/android-so.yml 
  pull_request:
    branches: [ "main" ]
    paths:
      - android-so/**
      - '*.json'
      - .github/workflows/android-so.yml 

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: test and publish coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: ./gradlew test jacocoTestReport coveralls
      
